services:
    paromailer.sender.factory:
        class: Paro\MailerBundle\Mailer\Sender\SenderFactory
        arguments:
          - "%paro_mailer.sender%"

    paromailer.template.factory:
        class: Paro\MailerBundle\Mailer\Template\TemplateFactory

    paromailer.template.engine.twig:
        class: Paro\MailerBundle\Mailer\Template\Twig\TwigTemplateEngine
        arguments:
            - "@twig"
        tags:
            -  { name: paromailer.template.engine, alias: 'twig' }

    paromailer.producer.factory:
        class: Paro\MailerBundle\Mailer\Storage\ProducerFactory

    paromailer.consumer.factory:
            class: Paro\MailerBundle\Mailer\Storage\ConsumerFactory

    paromailer.producer:
        class: Paro\MailerBundle\Mailer\Storage\ProducerInterface
        factory: ["@paromailer.producer.factory", createNewProducer]
        arguments:
            - "%paro_mailer.storage.type%"
            - "%paro_mailer.storage.parameters%"

    paromailer.consumer:
        class: Paro\MailerBundle\Mailer\Storage\ConsumerInterface
        factory: ["@paromailer.consumer.factory", createNewConsumer]
        arguments:
            - "%paro_mailer.storage.type%"
            - "%paro_mailer.storage.parameters%"
            - '@paromailer.sender.factory'

    paromailer.mailer:
        class: Paro\MailerBundle\Mailer\Mailer
        arguments: ['@paromailer.producer', '@paromailer.consumer', '@paromailer.template.factory']